import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as Material from '@angular/material'


@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    Material.MatToolbarModule,
    Material.MatButtonModule,
    Material.MatIconModule,
    Material.MatMenuModule,
    Material.MatCardModule,
    Material.MatExpansionModule,
    Material.MatInputModule,
    Material.MatStepperModule,
    Material.MatSelectModule,
    Material.MatNativeDateModule,
    Material.MatDatepickerModule,
    Material.MatProgressSpinnerModule,
    Material.MatTabsModule,
    Material.MatAutocompleteModule,
    Material.MatRadioModule,
    Material.MatCheckboxModule,
    Material.MatListModule,
    Material.MatChipsModule,
    Material.MatSidenavModule,
    Material.MatSlideToggleModule,
    Material.MatButtonToggleModule,
    Material.MatSliderModule,
    Material.MatTableModule,
    Material.MatPaginatorModule,
    Material.MatSortModule,

  ],
  exports:[
    Material.MatToolbarModule,
    Material.MatButtonModule,
    Material.MatIconModule,
    Material.MatMenuModule,
    Material.MatCardModule,
    Material.MatExpansionModule,
    Material.MatInputModule,
    Material.MatStepperModule,
    Material.MatSelectModule,
    Material.MatNativeDateModule,
    Material.MatDatepickerModule,
    Material.MatProgressSpinnerModule,
    Material.MatTabsModule,
    Material.MatAutocompleteModule,
    Material.MatRadioModule,
    Material.MatCheckboxModule,
    Material.MatListModule,
    Material.MatChipsModule,
    Material.MatSidenavModule,
    Material.MatSlideToggleModule,
    Material.MatButtonToggleModule,
    Material.MatSliderModule,
    Material.MatTableModule,
    Material.MatPaginatorModule,
    Material.MatSortModule,
  ]
})
export class MaterialModule { }
